apiVersion: apps/v1
kind: Deployment
metadata:
  name: graceful-shutdown-no-sleep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graceful-shutdown-no-sleep
  template:
    metadata:
      labels:
        app: graceful-shutdown-no-sleep
    spec:
      containers:
        - name: nginx
          image: graceful-shutdown-no-sleep:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: graceful-shutdown-no-sleep
spec:
  type: NodePort
  selector:
    app: graceful-shutdown-no-sleep
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30009